### ISSUE TITLE
Feature Request: Add ability to provide custom sorting of group children

### ISSUE THREAD

**Issue by jflan-dd** [MobileNativeFoundation/rules_xcodeproj#3131]
We organize our modules into layers where each layer can only import code from the layer “below” it. In our current generated project file we sort those layer folders to reflect that hierarchy. We'd like to be able to provide custom sorting logic for specific Xcode project groups to communicate that hierarchy to developers in the project structure.

Here's our existing XcodeGen customization:
```
options:
  groupOrdering:
    - order:
        - ConsumerApp
        - Packages
        - CommonPackages
    - pattern: "Packages"
      order:
        - AppClip
        - AppIntegration
        - LegacyApp
        - Modules
        - Routing
        - DomainInterfaces
        - Services
        - Capabilities
        - Networking
        - Foundation
        - Resources
```
